### ISSUE TITLE
[Tracking Issue] Add Types for All Already Present Modules in ScriptModules

### ISSUE THREAD

**Issue by pirak** [crowbartools/firebot-custom-scripts-types#2]
This is a tracking issue to make splitting work between several people easier.

The type `ScriptModules` does not contain all modules that Firebot actually makes available:
https://github.com/crowbartools/Firebot/blob/v5/backend/common/handlers/custom-scripts/custom-script-helpers.js (function `buildModules`).

For each module a corresponding type should be created that contains the functions that should be exposed. Additionally, types needed to call those functions should be added (e.g. `Currency`, `Counter`, …).

- [x] twitchChat
- [x] twitchApi (@ebiggz, #7)
- [x] httpServer
- [x] effectManager
- [x] conditionManager
- [x] restrictionManager
- [x] commandManager (@pirak, #14)
- [x] eventManager
- [x] eventFilterManager
- [x] replaceVariableManager
- [x] integrationManager (@patchtechtwitch, #?)
- [x] customVariableManager (@pirak, #8)
- [x] firebotRolesManager (@pirak, #9)
- [ ] timerManager
- [x] gameManager (@pirak, #12)
- [x] currencyManager (@patchtechtwitch, #4)
- [x] currencyDb (@patchtechtwitch, #13)
- [x] userDb (@pirak, #6)
- [x] quotesManager (@pirak, #5)
- [x] frontendCommunicator
- [x] counterManager (@pirak, #5)
- [x] utils (@pirak, #11)

**Comment by patchtechtwitch** [comment]
Since I'm playing around in the area, i'll see if I can't pick up "currencyManager"

**Comment by patchtechtwitch** [comment]
currencyDb

**Comment by patchtechtwitch** [comment]
I'll grab integrationManager and timerManager

**Comment by ebiggz** [comment]
Closing this as completed! If anyone ends up needing types for `timerManager`, please make a new issue for it 👍🏻
